### ISSUE TITLE
Allow overriding image/tag for webhook

### ISSUE THREAD

**Issue by joelddiaz** [mondoohq/mondoo-operator#164]
Similar to the work done in https://github.com/mondoohq/mondoo-operator/pull/144 , add the ability to set an alternative image/tag for the webhook in the MondooAuditConfig CRD.

The main difference from the node/workload is that the default image/tag for the webhook is different than what is used for the node/workload scanning. The webhook uses the mondoo-operator container image (ghcr.io/mondoohq/mondoo-operator:VERSION).

**Comment by chris-rock** [comment]
```
apiVersion: k8s.mondoo.com/v1alpha1
kind: MondooAuditConfig
metadata:
  name: mondoo-client
  namespace: mondoo-operator
spec:
  workloads:
    enable: true
    serviceAccount: mondoo-operator-workload
  nodes:
    enable: true
  webhooks:
    enable: false
    image:
      name: xx
      tag: xx
  mondooSecretRef: mondoo-client
  ```
  
  as in #144 the definition is optional for the user
