### ISSUE TITLE
Exclude docs changes from running all the tests 

### ISSUE THREAD

**Issue by chris-rock** [mondoohq/mondoo-operator#224]
**What is not working as you expected it?**

Docs changes can be added quicker:

```
on:
  push:
    paths-ignore:
      - 'docs/**'
``` 

https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore
