### ISSUE TITLE
GKE node detection not working

### ISSUE THREAD

**Issue by chris-rock** [mondoohq/mondoo-operator#347]
**Describe the bug**

For GKE, the normal platform detection does not work since `/etc/hostname` does not exist.

**To Reproduce**

Run current operator on GKE

**Expected behavior**

Node scans just work

**Screenshots**

```
→ discover related assets for 1 asset(s)
DBG run resolver resolver="Standard Resolver" resolver-id=fs
DBG establish motor connection
→ load fs mountdir=/mnt/host
DBG could not execute os release detection command error="filesearch transport does not implement RunCommand"
DBG could not execute os release detection command error="filesearch transport does not implement RunCommand"
DBG platform> we do not know the linux system, but we do our best in guessing
DBG platform> detected os family=["linux","unix","os"] platform=cos
DBG could not run hostname command error="filesearch transport does not implement RunCommand"
DBG could not read /etc/hostname file
DBG could not determine platform id error="could not detect hostname" detector=hostname
→ resolved assets resolved-assets=0
x could not connect to asset error="could not determine a platform identifier" asset=
DBG synchronize asset found=0
DBG call service url=https://api.edge.mondoo.com/AssetStore/SyncAssets
```

**Additional context**

To solve this problem, we just need to inject a unique id for the asset from outside. To achieve this we need to adapt the `inventory.yml` slightly:

```
    apiVersion: v1
    kind: Inventory
    metadata:
      name: mondoo-k8s-inventory
      labels:
        environment: production
    spec:
      assets:
        - id: host
          name: {node-name}
          id_detector:
            - machine-id
          connections:
            - host: /mnt/host
              backend: fs
```
