### ISSUE TITLE
Switch disable config to enable config

### ISSUE THREAD

**Issue by chris-rock** [mondoohq/mondoo-operator#36]
switch config from:

```  
  kubeapi:
    disable: false
  kubenodes:
    disable: false
```

to:

```  
  kubeapi:
    enable: true 
  kubenodes:
    enable: true
```
