### ISSUE TITLE
Improve config names

### ISSUE THREAD

**Issue by chris-rock** [mondoohq/mondoo-operator#42]
I was thinking about the current naming

- MondooConfig: very generic
- kubeNodes not clear what this refers to
- kubeAPI as well

What if we structure this under `MondooAuditConfig`. Then it is clear that everything is related to Audit. Then we can use `resources` and `nodes` 

```
apiVersion: k8s.mondoo.com/v1alpha1
kind: MondooAuditConfig
metadata:
  name: mondoo-client
  namespace: mondoo-operator-system
data:
  mondooSecretRef: "name"
  resources:
    enable: true
  nodes:
    enable: true
```
