### ISSUE TITLE
Unclear semantic of `skipContainerResolution` flag

### ISSUE THREAD

**Issue by chris-rock** [mondoohq/mondoo-operator#474]
**What is not working as you expected it?**

When we 

```yaml
apiVersion: k8s.mondoo.com/v1alpha2
kind: MondooOperatorConfig
metadata:
  name: mondoo-operator-config
spec:
  skipContainerResolution: true
```

For the `MondooOperatorConfig` we use `skipContainerResolution` to enable/disable the digest resolution for images. The current name can be misinterpreted as disabling Container resolution from pods which can be enabled/disabled in the `MondooAuditConfig`

**Where on the platform does it happen?**

all

**How do we replicate the issue?**

see above

**Expected behavior (i.e. solution)**

We should use a more descriptive name like `skipImageDigestResolution` to avoid confusion with settings in the `MondooAuditConfig`

**Other Comments**
