### ISSUE TITLE
Scan container images of running container

### ISSUE THREAD

**Issue by chris-rock** [mondoohq/mondoo-operator#57]
To include the scanning of the container images from running container,  we need to adapt the inventory to include the discovery flag `container-images`

```
apiVersion: v1
kind: Inventory
metadata:
  name: mondoo-k8s-inventory
  labels:
    environment: production
spec:
  assets:
    - id: minikube
      connections:
        - backend: k8s
          discover:
            targets:
              - container-images
```
