### ISSUE TITLE
Set `privileged` explicitly to false

### ISSUE THREAD

**Issue by czunker** [mondoohq/mondoo-operator#718]
**Is your feature request related to a problem? Please describe.**
Currently, we only have set `privileged` implicitly to `false` by not specifying it:
```
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 101
```
This flags the operator in MQL queries where someone searches for `...privileged == false`.

**Describe the solution you'd like**
We should explicitly set it to `false`.

**Describe alternatives you've considered**
We could keep it as is.

**Additional context**
This does not change functionality. It only makes it more explicit.
