### ISSUE TITLE
Helm installation fails when using Flux

### ISSUE THREAD

**Issue by nliakm** [mondoohq/mondoo-operator#751]
When trying to install the mondoo-operator via Helm and Flux, the installation fails due to following error:
```
Helm install failed: error while running post render on files: map[string]interface {}(nil): yaml: unmarshal errors: line 18: mapping key "app.kubernetes.io/name" already defined at line 17
```

The reason for this behaviour is described [here](https://github.com/fluxcd/flux2/issues/1522#issue-921347907):

> Unlike Helm, the Kustomize yaml parser (kyaml) does not accept duplicate keys, while Helm drops the duplicates, Kustomize errors out. This impacts helm-controller as it uses kustomize/kyaml to label objects reconciled by a HelmRelease.

The duplicated keys are inside the rendered `Deployment` and `Service` manifests.
```
---
# Source: mondoo-operator/templates/metrics-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: mondoo-operator-controller-manager-metrics-service
  labels:
    helm.sh/chart: mondoo-operator-1.11.1
    app.kubernetes.io/name: mondoo-operator
    app.kubernetes.io/instance: mondoo-operator
    app.kubernetes.io/version: "1.11.1"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: mondoo-operator # << duplicate keys
    app.kubernetes.io/name: mondoo-operator # << duplicate keys
    app.kubernetes.io/instance: mondoo-operator
  ports:
  - name: metrics
    port: 8080
    protocol: TCP
    targetPort: metrics
---
# Source: mondoo-operator/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mondoo-operator-controller-manager
  labels:
    helm.sh/chart: mondoo-operator-1.11.1
    app.kubernetes.io/name: mondoo-operator
    app.kubernetes.io/instance: mondoo-operator
    app.kubernetes.io/version: "1.11.1"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mondoo-operator # << duplicate keys
      app.kubernetes.io/name: mondoo-operator # << duplicate keys
      app.kubernetes.io/instance: mondoo-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mondoo-operator # << duplicate keys
        app.kubernetes.io/name: mondoo-operator # << duplicate keys
        app.kubernetes.io/instance: mondoo-operator
      annotations:
...
```
The solution to fix it, would be probably to just delete the hardcoded `app.kubernetes.io/name: mondoo-operator` inside the `deployment.yaml` and `metrics-service.yaml`, because they will get templated anyway when rendering the manifest files.
