### ISSUE TITLE
MondooAuditConfig should support image digest

### ISSUE THREAD

**Issue by czunker** [mondoohq/mondoo-operator#759]
**Is your feature request related to a problem? Please describe.**
-

**Describe the solution you'd like**
You can specify a specific image for the scanner and the admission controller:
```
                image:
                    properties:
                      name:
                        type: string
                      tag:
                        type: string
```
But this section only supports tags. It would be nice to also support image digests.

**Describe alternatives you've considered**
-
