### ISSUE TITLE
Simplify audit config

### ISSUE THREAD

**Issue by chris-rock** [mondoohq/mondoo-operator#76]
With #54 we renamed the configuration to `MondooAuditConfig` which is great but the properties names can be optimised. A current sample config looks like:

```yaml
apiVersion: k8s.mondoo.com/v1alpha1
kind: MondooAuditConfig
metadata:
  name: mondoo-client
  namespace: mondoo-operator-system
spec:
  workloads:
    enable: true
    workloadserviceaccount: mondoo-operator-workload
    replicas: 1
  nodes:
    enable: true
  mondoosecretref: mondoo-client
 
```

The following entries are confusing:

- k8s uses camelCase for yaml attributes as default, we should adapt
- `workloadserviceaccount ` should be renamed to `serviceAccountName` since it is already part of the `workload` property
- `replicas` should be removed for now since the Mondoo does not support replicas yet. Right now the replica is always one. We are going to re-introduce that at a later point when we have a proper queuing mechanism.
- `mondoosecretref` should be renamed to `mondooSecretRef`
